# Generated by Django 3.2.18 on 2023-02-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Other', 'Other'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Home & Garden', 'Home & Garden'), ('Toys & Game', 'Toys & Garden'), ('Sport & Outdoor', 'Sport & Outdoor'), ('Pet Supply', 'Pet Supply'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Car & Motorbike', 'Car & Motorbike')], default='Other', max_length=50)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
