# Generated by Django 3.2.18 on 2023-02-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Books', 'Books'), ('Home & Garden', 'Home & Garden'), ('Electronics', 'Electronics'), ('Other', 'Other'), ('Beauty', 'Beauty'), ('Pet Supply', 'Pet Supply'), ('Car & Motorbike', 'Car & Motorbike'), ('Fashion', 'Fashion'), ('Sport & Outdoor', 'Sport & Outdoor'), ('Toys & Game', 'Toys & Garden')], default='Other', max_length=50),
        ),
    ]
