# Generated by Django 3.2.18 on 2023-02-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Sport & Outdoor', 'Sport & Outdoor'), ('Other', 'Other'), ('Beauty', 'Beauty'), ('Toys & Game', 'Toys & Garden'), ('Electronics', 'Electronics'), ('Pet Supply', 'Pet Supply'), ('Fashion', 'Fashion'), ('Car & Motorbike', 'Car & Motorbike'), ('Home & Garden', 'Home & Garden'), ('Books', 'Books')], default='Other', max_length=50),
        ),
    ]
