# Generated by Django 3.2.18 on 2023-02-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AddField(
            model_name='category',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Other', 'Other'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Home & Garden', 'Home & Garden'), ('Toys & Garden', 'Toys & Garden'), ('Sport & Outdoor', 'Sport & Outdoor'), ('Pet Supply', 'Pet Supply'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Car & Motorbike', 'Car & Motorbike')], default='Other', max_length=50),
        ),
    ]
