# Generated by Django 3.2.17 on 2023-02-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
    ]
