# Generated by Django 3.2.17 on 2023-02-11 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_products_category'),
        ('likes', '0002_alter_like_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked', to='products.products'),
        ),
    ]
