# Generated by Django 3.2.18 on 2023-02-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Other', 'Other'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Home & Garden', 'Home & Garden'), ('Toys & Garden', 'Toys & Garden'), ('Sport & Outdoor', 'Sport & Outdoor'), ('Pet Supply', 'Pet Supply'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Car & Motorbike', 'Car & Motorbike')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
