# Generated by Django 3.2.17 on 2023-02-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_product'),
        ('products', '0005_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, choices=[('Other', 'Other'), ('Fashion', 'Fashion'), ('Beauty', 'Beauty'), ('Home & Garden', 'Home & Garden'), ('Toys & Game', 'Toys & Garden'), ('Sport & Outdoor', 'Sport & Outdoor'), ('Pet Supply', 'Pet Supply'), ('Books', 'Books'), ('Electronics', 'Electronics'), ('Car & Motorbike', 'Car & Motorbike')], on_delete=django.db.models.deletion.CASCADE, related_name='category', to='category.category'),
        ),
    ]
